-- migrate:up
ALTER TABLE buyings MODIFY updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT NOW();

ALTER TABLE sellings MODIFY updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT NOW();

ALTER TABLE deals MODIFY updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT NOW();
-- migrate:down